import React, { useState } from "react";
import Head from "next/head";
import styles from "@/styles/Home.module.css";
import PrefCheckbox from "@/components/PrefCheckbox";
import PopulationChart from "@/components/PopulationChart";

export default function Home() {
  const [selectedPrefCodes, setSelectedPrefCodes] = useState<number[]>([]);

  const handlePrefectureChange = (prefCode: number, checked: boolean) => {
    if (checked) {
      setSelectedPrefCodes((prev) => [...prev, prefCode]);
    } else {
      setSelectedPrefCodes((prev) => prev.filter((code) => code !== prefCode));
    }
  };

  return (
    <>
      <Head>
        <title>都道府県別の総人口推移グラフ</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>都道府県一覧</h1>
      <main className={styles.main}>
        <PrefCheckbox onChange={handlePrefectureChange} />
        {selectedPrefCodes.length > 0 && (
          <PopulationChart
            prefCodes={selectedPrefCodes}
            populationType="総人口"
          />
        )}
      </main>
    </>
  );
}
