import React, { useState } from "react";
import Head from "next/head";
import styles from "@/styles/Home.module.css";
import PrefCheckbox from "@/components/PrefCheckbox";
import PopulationChart from "@/components/showPopulationChart";

export default function Home() {
  const [selectedPrefCodes, setSelectedPrefCodes] = useState<number[]>([]);
  const [populationType, setPopulationType] = useState("総人口");

  const handlePrefectureChange = (prefCode: number, checked: boolean) => {
    if (checked) {
      setSelectedPrefCodes((prev) => [...prev, prefCode]);
    } else {
      setSelectedPrefCodes((prev) => prev.filter((code) => code !== prefCode));
    }
  };

  return (
    <>
      <Head>
        <title>都道府県別の総人口推移グラフ</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>都道府県</h1>
      <main className={styles.main}>
        <PrefCheckbox onChange={handlePrefectureChange} />
        <div className={styles.populationTypeSelector}>
          <label>
            <input
              type="radio"
              name="populationType"
              value="総人口"
              checked={populationType === "総人口"}
              onChange={() => setPopulationType("総人口")}
            />
            総人口
          </label>
          <label>
            <input
              type="radio"
              name="populationType"
              value="年少人口"
              checked={populationType === "年少人口"}
              onChange={() => setPopulationType("年少人口")}
            />
            年少人口
          </label>
          <label>
            <input
              type="radio"
              name="populationType"
              value="生産年齢人口"
              checked={populationType === "生産年齢人口"}
              onChange={() => setPopulationType("生産年齢人口")}
            />
            生産年齢人口
          </label>
          <label>
            <input
              type="radio"
              name="populationType"
              value="老年人口"
              checked={populationType === "老年人口"}
              onChange={() => setPopulationType("老年人口")}
            />
            老年人口
          </label>
        </div>
        {selectedPrefCodes.length > 0 && (
          <PopulationChart
            prefCodes={selectedPrefCodes}
            populationType={populationType}
          />
        )}
      </main>
    </>
  );
}
