import React, { useState } from "react";
import Head from "next/head";
import styles from "@/styles/Home.module.css";
import PrefCheckbox from "@/components/prefCheckbox";
import PopulationChart from "@/components/showPopulationChart";
import PopulationTypeSelector from "@/components/populationTypeSelector";

export default function Home() {
  const [selectedPrefs, setSelectedPrefs] = useState<
    { code: number; name: string }[]
  >([]);
  const [populationType, setPopulationType] = useState("総人口");

  const handlePrefectureChange = (
    selectedPrefs: { code: number; name: string }[]
  ) => {
    setSelectedPrefs(selectedPrefs);
  };

  const handlePopulationTypeChange = (
    event: React.ChangeEvent<HTMLInputElement>
  ) => {
    setPopulationType(event.target.value);
  };

  return (
    <>
      <Head>
        <title>都道府県別の総人口推移グラフ</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>都道府県</h1>
      <main className={styles.main}>
        <PrefCheckbox onChange={handlePrefectureChange} />
        <PopulationTypeSelector
          populationType={populationType}
          onChange={handlePopulationTypeChange}
        />
        {selectedPrefs.length > 0 && (
          <PopulationChart
            selectedPrefs={selectedPrefs}
            populationType={populationType}
          />
        )}
      </main>
    </>
  );
}
